### ISSUE TITLE
`legacy` info missing?

### ISSUE THREAD

**Issue by NfNitLoop** [nogira/deno-twitter-guest-api#1]
Wish I'd found this library a couple days ago before trying to implement this myself. :p 

Looks like the return value may have been changed since you last touched this though.  

This test:

```typescript
import * as dtga from "https://deno.land/x/deno_twitter_guest_api@v0.2.0/mod.ts";

let tweets = await dtga.urlToTweets("https://twitter.com/POTUS/status/1606439512141434882")
console.log(JSON.stringify(tweets, null, 2))
```

is giving this error:

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id_str')
        id: tweetContents.legacy.id_str,
                                 ^
    at parseTweetContents (https://deno.land/x/deno_twitter_guest_api@v0.2.0/src/parseTweetContents.ts:16:34)
    at tweetModuleGroupToTweets (https://deno.land/x/deno_twitter_guest_api@v0.2.0/src/main/urlToTweets.ts:135:43)
    at tweetGroupToTweets (https://deno.land/x/deno_twitter_guest_api@v0.2.0/src/main/urlToTweets.ts:150:24)
    at Module.urlToTweets (https://deno.land/x/deno_twitter_guest_api@v0.2.0/src/main/urlToTweets.ts:61:26)
```

**Comment by NfNitLoop** [comment]
FWIW, I was using [zod] in my own attempt and it's great at validating JSON data formats! :D  

[zod]: https://github.com/colinhacks/zod

**Comment by nogira** [comment]
forgot to add new version to denoland. fixed now
